server:
  port: 8080

spring:
  application:
    name: gmg

  datasource:
    url: "${DB_URL}"
    username: "${DB_NAME}"
    password: "${DB_PWD}"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${GOOGLE_CLIENT_ID}"
            client-secret: "${GOOGLE_CLIENT_SECRET}"
            redirect-uri: "${GOOGLE_REDIRECT_URL}"
            scope: profile, email
            authorization-grant-type: authorization_code
