services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana  # Grafana 데이터 유지
    depends_on:
      - prometheus
    networks:
      - monitoring

volumes:
  grafana-storage:
    driver: local

networks:
  monitoring:
    driver: bridge