global:
  scrape_interval: 15s # 기본 메트릭 수집 주기
  evaluation_interval: 15s # 규칙 평가 주기

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus' # Spring Boot Actuator의 Prometheus 엔드포인트
    scheme: http
    static_configs:
      - targets:
          - 'host.docker.internal:8080' # 도커로 띄웠을 때는 localhost 하면 도커 컨테이너가 아니여서 컨테이너 호스트명을 이렇게 해줘야 함
#          - 'localhost:8080'